//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackTraining.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ovelse
    {
        public int Ovelse_ID { get; set; }
        public string OvelseNavn { get; set; }
        public int Gentagelser { get; set; }
        public System.DateTime Dato { get; set; }
        public int Bruger_ID { get; set; }
        public string Billede { get; set; }
    
        public virtual Bruger Bruger { get; set; }
    }
}
