//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackTraining.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Ovelser
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Ovelser()
        {
            this.Rekorder2 = new HashSet<Rekorder2>();
        }
    
        public int OvelseId { get; set; }
        public string OvelseNavn { get; set; }
        public string Billede { get; set; }
        public string Primære { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Rekorder2> Rekorder2 { get; set; }
    }
}
