//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackTraining.Views
{
    using System;
    using System.Collections.Generic;
    
    public partial class Rekorder2
    {
        public int RekordId { get; set; }
        public int OvelseId { get; set; }
        public string BrugerId { get; set; }
        public System.DateTime dato { get; set; }
        public string Gentagelser { get; set; }
    
        public virtual AspNetUser AspNetUser { get; set; }
        public virtual Ovelser Ovelser { get; set; }
    }
}
